version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install packages
          command: npm ci
      - run:
          name: Run Tests
          command: npx jest
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

workflows:
  version: 2
  orb-free-workflow:
    jobs:
      - test
